baseURL = "https://y2kappa.github.io/beautiful-code/"
languageCode = "en-us"
title = "Beautiful Code"
theme = "archie"
publishDir = "docs"

[params]
	mode="dark" # color-mode → light,dark or auto
	featherIconsCDN=true
	subtitle = "👨‍💻 Snippets that make you want to clap 👏 in awe 🙌. Rust 🦀 OCaml 🐪 Python 🐍 C++"
