baseURL = "https://y2kappa.github.io/blog/"
languageCode = "en-us"
title = ""
theme = "hugo-PaperMod"
publishDir = "docs"
googlefonts = ["Droid Sans", "Fira Mono"]
fontbody = 'Droid Sans'
fontcode = 'Fira Mono'

[params]
	mode="dark" # color-mode → light,dark or auto
	featherIconsCDN=true
	subtitle = "Me talking to my future me."

[params.homeInfoParams]
	Title = "Hi there 👋 🐵"
	Content = "My name is Marius, I sometimes think about stuff. Sometimes that stuff is programming. Most of the times it's me discovering old lessons and relearning old stuff."
